[package]
name = "zzignal"
version = "0.1.20"
edition = "2021"

[lib]
name = "zzignal"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22.6", features = ["extension-module"] }
rand = "0.8"
rand_distr = "0.4"
statrs = "0.16"

