[package]
name = "zzignal"
version = "0.1.19"
edition = "2021"

[lib]
name = "zzignal"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3 = { version = "0.22.6", features = ["extension-module"] }

