[package]
name = "zzignal"
version = "0.1.18"
edition = "2021"

[lib]
name = "zzignal"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22", features = ["extension-module"] }
rand = "0.8"
rand_distr = "0.4"
nalgebra = "0.34.1"
rayon = "1.10"

